# Generated by Django 4.2a1 on 2023-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_match_options_alter_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
