# Generated by Django 4.1 on 2023-01-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='capacity',
        ),
    ]
