# Generated by Django 4.1 on 2023-01-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_remove_section_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
